In [104]:
!pip install category_encoders

In [0]:
import numpy as np
import pandas as pd
import category_encoders as ce

from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import SGD
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split

In [106]:
df = pd.read_csv("labelled_bird_sample.csv")

print(df.shape)

df.head()

(103992, 16)


name  observ_count  ... seas_reg_rare target
0     Magnolia Warbler             2  ...      Uncommon      1
1     Great Blue Heron             2  ...        Common      0
2        Purple Martin             6  ...        Common      0
3  Common Yellowthroat             3  ...        Common      0
4       Eastern Towhee             3  ...        Common      0

[5 rows x 16 columns]

In [107]:
df.dtypes

name              object
observ_count       int64
country           object
state             object
county            object
latitude         float64
longitude        float64
observ_date       object
month              int64
season            object
county_state      object
State             object
CountyName        object
RegionName        object
seas_reg_rare     object
target             int64
dtype: object

In [0]:
features = ['name', 'season', 'RegionName']
target = 'target'

X = df[features].values
y = df[target].values

In [0]:
encoder = ce.CatBoostEncoder()

X_encoded = encoder.fit_transform(X, y)

# target_encoder = ce.OneHotEncoder()

# y_encoded = target_encoder.fit_transform(y)

In [0]:
y = to_categorical(y)

In [0]:
scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(X_encoded)

In [139]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((77994, 3), (25998, 3), (77994, 3), (25998, 3))

In [0]:
opt = SGD(lr=0.01, momentum=0.9)

model = Sequential()

model.add(Dense(3, input_dim=3, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

In [141]:
X_train

array([[0.04664309, 0.55918695, 0.2278755 ],
       [0.10481713, 0.569044  , 0.28444879],
       [0.48623325, 0.6029662 , 0.39868874],
       ...,
       [0.1613006 , 0.58458934, 0.26700679],
       [0.68083451, 0.5931317 , 0.29758629],
       [0.31439303, 0.60512414, 0.28315587]])

In [142]:
y_train

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]], dtype=float32)

In [143]:
history = model.fit(X_train, y_train, epochs=30, validation_data=(X_test, y_test))

Epoch 1/30
2438/2438 [==============================] - 4s 1ms/step - loss: 0.5812 - accuracy: 0.7532 - val_loss: 0.5505 - val_accuracy: 0.7651
Epoch 2/30
2438/2438 [==============================] - 4s 1ms/step - loss: 0.5553 - accuracy: 0.7632 - val_loss: 0.5494 - val_accuracy: 0.7651
Epoch 3/30
2438/2438 [==============================] - 4s 1ms/step - loss: 0.5549 - accuracy: 0.7629 - val_loss: 0.5502 - val_accuracy: 0.7649
Epoch 4/30
2438/2438 [==============================] - 4s 1ms/step - loss: 0.5538 - accuracy: 0.7630 - val_loss: 0.5481 - val_accuracy: 0.7657
Epoch 5/30
2438/2438 [==============================] - 4s 1ms/step - loss: 0.5520 - accuracy: 0.7636 - val_loss: 0.5450 - val_accuracy: 0.7668
Epoch 6/30
2438/2438 [==============================] - 3s 1ms/step - loss: 0.5498 - accuracy: 0.7637 - val_loss: 0.5427 - val_accuracy: 0.7669
Epoch 7/30
2438/2438 [==============================] - 4s 1ms/step - loss: 0.5476 - accuracy: 0.7646 - val_loss: 0.5439 - val_accuracy:

In [144]:
model.summary()

Model: "sequential_24"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_59 (Dense)             (None, 3)                 12        
_________________________________________________________________
dense_60 (Dense)             (None, 3)                 12        
Total params: 24
Trainable params: 24
Non-trainable params: 0
_________________________________________________________________


In [0]:
opt = SGD(lr=0.01, momentum=0.9)

model = Sequential()

model.add(Dense(3, input_dim=3, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

In [146]:
model.summary()

Model: "sequential_25"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_61 (Dense)             (None, 3)                 12        
_________________________________________________________________
dropout_18 (Dropout)         (None, 3)                 0         
_________________________________________________________________
dense_62 (Dense)             (None, 3)                 12        
_________________________________________________________________
dropout_19 (Dropout)         (None, 3)                 0         
_________________________________________________________________
dense_63 (Dense)             (None, 3)                 12        
Total params: 36
Trainable params: 36
Non-trainable params: 0
_________________________________________________________________


In [147]:
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test)) 

Epoch 1/50
2438/2438 [==============================] - 4s 2ms/step - loss: 0.6722 - accuracy: 0.7173 - val_loss: 0.6057 - val_accuracy: 0.7448
Epoch 2/50
2438/2438 [==============================] - 4s 1ms/step - loss: 0.6321 - accuracy: 0.7367 - val_loss: 0.5807 - val_accuracy: 0.7589
Epoch 3/50
2438/2438 [==============================] - 4s 1ms/step - loss: 0.6291 - accuracy: 0.7375 - val_loss: 0.5790 - val_accuracy: 0.7613
Epoch 4/50
2438/2438 [==============================] - 4s 1ms/step - loss: 0.6310 - accuracy: 0.7376 - val_loss: 0.5782 - val_accuracy: 0.7629
Epoch 5/50
2438/2438 [==============================] - 4s 1ms/step - loss: 0.6307 - accuracy: 0.7376 - val_loss: 0.5745 - val_accuracy: 0.7611
Epoch 6/50
2438/2438 [==============================] - 4s 1ms/step - loss: 0.6311 - accuracy: 0.7375 - val_loss: 0.5791 - val_accuracy: 0.7615
Epoch 7/50
2438/2438 [==============================] - 4s 1ms/step - loss: 0.6308 - accuracy: 0.7364 - val_loss: 0.5710 - val_accuracy:

In [148]:
features = ['name', 'season', 'RegionName', 'county_state', 'latitude', 'longitude']
target = 'target'

X = df[features].values
y = df[target].values

encoder = ce.CatBoostEncoder()

X_encoded = encoder.fit_transform(X, y)

scaler = MinMaxScaler()

X_scaled = scaler.fit_transform(X_encoded)

y = to_categorical(y)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((77994, 6), (25998, 6), (77994, 3), (25998, 3))

In [151]:
y

array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [0]:
#opt = SGD(lr=0.01, momentum=0.9)

model = Sequential()

model.add(Dense(6, input_dim=6, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [155]:
history = model.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test)) 

Epoch 1/100
2438/2438 [==============================] - 4s 2ms/step - loss: 0.7379 - accuracy: 0.6793 - val_loss: 0.5902 - val_accuracy: 0.7619
Epoch 2/100
2438/2438 [==============================] - 4s 2ms/step - loss: 0.6262 - accuracy: 0.7167 - val_loss: 0.5697 - val_accuracy: 0.7627
Epoch 3/100
2438/2438 [==============================] - 4s 1ms/step - loss: 0.6105 - accuracy: 0.7224 - val_loss: 0.5610 - val_accuracy: 0.7560
Epoch 4/100
2438/2438 [==============================] - 4s 1ms/step - loss: 0.6038 - accuracy: 0.7247 - val_loss: 0.5598 - val_accuracy: 0.7497
Epoch 5/100
2438/2438 [==============================] - 4s 1ms/step - loss: 0.6020 - accuracy: 0.7249 - val_loss: 0.5557 - val_accuracy: 0.7517
Epoch 6/100
2438/2438 [==============================] - 4s 1ms/step - loss: 0.5997 - accuracy: 0.7267 - val_loss: 0.5586 - val_accuracy: 0.7447
Epoch 7/100
2438/2438 [==============================] - 4s 1ms/step - loss: 0.5990 - accuracy: 0.7253 - val_loss: 0.5520 - val_ac

In [0]:
model = Sequential()

model.add(Dense(24, input_dim=6, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(8, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

In [159]:
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test)) 

Epoch 1/50
2438/2438 [==============================] - 4s 2ms/step - loss: 0.6081 - accuracy: 0.7382 - val_loss: 0.5386 - val_accuracy: 0.7666
Epoch 2/50
2438/2438 [==============================] - 4s 1ms/step - loss: 0.5652 - accuracy: 0.7602 - val_loss: 0.5384 - val_accuracy: 0.7593
Epoch 3/50
2438/2438 [==============================] - 4s 1ms/step - loss: 0.5628 - accuracy: 0.7605 - val_loss: 0.5392 - val_accuracy: 0.7599
Epoch 4/50
2438/2438 [==============================] - 4s 2ms/step - loss: 0.5587 - accuracy: 0.7628 - val_loss: 0.5443 - val_accuracy: 0.7543
Epoch 5/50
2438/2438 [==============================] - 4s 2ms/step - loss: 0.5572 - accuracy: 0.7618 - val_loss: 0.5312 - val_accuracy: 0.7703
Epoch 6/50
2438/2438 [==============================] - 4s 2ms/step - loss: 0.5575 - accuracy: 0.7622 - val_loss: 0.5325 - val_accuracy: 0.7705
Epoch 7/50
2438/2438 [==============================] - 4s 1ms/step - loss: 0.5560 - accuracy: 0.7635 - val_loss: 0.5400 - val_accuracy:

In [0]:
model = Sequential()

model.add(Dense(24, input_dim=6, activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(12, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(6, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3, activation='relu'))

model.compile(loss='categorical_hinge', optimizer=opt, metrics=['accuracy'])

In [165]:
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test)) 

Epoch 1/50
2438/2438 [==============================] - 4s 2ms/step - loss: 0.5593 - accuracy: 0.7282 - val_loss: 0.4865 - val_accuracy: 0.7648
Epoch 2/50
2438/2438 [==============================] - 4s 2ms/step - loss: 0.5181 - accuracy: 0.7527 - val_loss: 0.4941 - val_accuracy: 0.7647
Epoch 3/50
2438/2438 [==============================] - 4s 2ms/step - loss: 0.5169 - accuracy: 0.7526 - val_loss: 0.4726 - val_accuracy: 0.7688
Epoch 4/50
2438/2438 [==============================] - 4s 2ms/step - loss: 0.5046 - accuracy: 0.7561 - val_loss: 0.4712 - val_accuracy: 0.7679
Epoch 5/50
2438/2438 [==============================] - 4s 2ms/step - loss: 0.4990 - accuracy: 0.7576 - val_loss: 0.4791 - val_accuracy: 0.7684
Epoch 6/50
2438/2438 [==============================] - 4s 2ms/step - loss: 0.4969 - accuracy: 0.7574 - val_loss: 0.4887 - val_accuracy: 0.7619
Epoch 7/50
2438/2438 [==============================] - 4s 2ms/step - loss: 0.4945 - accuracy: 0.7580 - val_loss: 0.4939 - val_accuracy:

### Trying to one-hot encode target

In [0]:
df['target'].value_counts()

0    68053
1    31665
2     4274
Name: target, dtype: int64

In [0]:
from sklearn.preprocessing import OneHotEncoder

encoder = ce.OneHotEncoder()

y = encoder.fit_transform(df['target'])